version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Client"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "nuget"
    directory: "/Api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dotnet"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
