@baseUrl = http://localhost:7071/api

### Get API Version
GET {{baseUrl}}/version
Accept: application/json

### Get Paged Users
GET {{baseUrl}}/users?pageNumber=1&pageSize=10
Accept: application/json

### Create User
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "jdoe",
    "email": "jdoe@example.com",
    "firstName": "John",
    "lastName": "Doe"
}
