name: Update Contributors

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributors:
    name: Update Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
